

---
all:
  hosts: #all hosts
    webserver1:
      ansible_host: 10.0.0.1
    webserver2:
      ansible_host: 10.0.0.2
    dbserver1:
      ansible_host: 10.10.0.100
    dbserver2:
      ansible_host: 10.10.0.200
  children: # define groups
    webservers: # webservers group
      hosts:
        webserver1:
        webserver2:
    dbservers: # db server group
      hosts:
        dbserver1:
        dbserver2: